### PR TITLE
update latest js and css

### PR DESCRIPTION
**Pull request by arlyxiao**
please update the latest js and css. it will fix an issue.
I use the min version
thanks

### CODE REVIEW

**Comment by Slashek** [comment]
I think it's better to be transparent of what js and css is here, i.e. we should not uglify them

**Comment by arlyxiao** [comment]
change the min into normal version, please check

**Comment by greshny** [comment]
good job :+1: 

@Slashek when you're going accept PR?

**Comment by Slashek** [comment]
accepted

**Comment by Slashek** [comment]
thx btw :+1:

**Pull request merged**
