### PR TITLE
Update bootstrap-select to v1.11.2

### PR DESCRIPTION
**Pull request by vincenzodev**

### CODE REVIEW

**Comment by teohm** [comment]
@Slashek Can help to merge and release a version? We love using your gem in our projects! 🙇 😘

**Comment by Slashek** [comment]
sure, thanks @teohm !

**Comment by vincenzodev** [comment]
TNX!!

**Comment by Slashek** [comment]
and thank you @vincenzodev for submitting this

**Comment by teohm** [comment]
Yay!!!!

**Pull request merged**
